services:
  e_comm_db:
    image: postgres:17.6
    container_name: e-commerce-pg-db
    restart: no
    environment:
      POSTGRES_DB: e_commerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qweasdzxc
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/pg
    networks:
      - backend
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - ${REDIS_SERVICE_PORT}
  minio:
    image: quay.io/minio/minio:latest
    ports:
      - ${MINIO_SERVICE_PORT}
      - ${MINIO_UI_PORT}
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":${MINIO_UI_PORT}"
    
volumes:
  pg_data:
  minio_data:

networks:
  backend:
